### ISSUE TITLE
no shadowed variable

### ISSUE THREAD

**Issue by TimMikeladze** [Intelight/tslint-intelight#5]
What is everyones thoughts on the `no-shadowed-variable` rule? I feel like it gets in the way, especially when writing tests. I'm proposing to disable it either entirely.

**Comment by alexyuly** [comment]
I like this rule because shadowed variables are unnecessarily confusing and shouldn't be used. However, if I keep my functions small enough, its value is limited. I wouldn't be too sad if you turn it off.
